In [1]:
import numpy as np
def vandermonde_matrix(vector,matrix_order):
    return np.fliplr(np.vander(vector,matrix_order))
x=vandermonde_matrix(np.array([2,3,5]),5)
print(x)

[[  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   5  25 125 625]]
